Assistance.create(name:"Capas lideres")
Assistance.create(name:"Capas dia 1")
Assistance.create(name:"Capas dia 2")
Assistance.create(name:"HiTec dia 1")
Assistance.create(name:"HiTec dia 2")

User.create(username:"staff", password:"staffs1234", password_confirmation:"staffs1234")
User.create(username:"lider", password:"lideres1234", password_confirmation:"lideres1234")
User.create(username:"team", password:"htteam18", password_confirmation:"htteam18")

Activity.create(name: "Jardin de las Carreras #1")
Activity.create(name: "Jardin de las Carreras #2")
Activity.create(name: "Jardin de las Carreras #3")
Activity.create(name: "Jardin de las Carreras #4")
Activity.create(name: "Jardin de las Carreras #5")
Activity.create(name: "Jardin de las Carreras #6")

Activity.create(name: "Aulas 7 #1")
Activity.create(name: "Aulas 7 #2")
Activity.create(name: "Aulas 7 #3")
Activity.create(name: "Aulas 7 #4")
Activity.create(name: "Aulas 7 #5")
Activity.create(name: "Aulas 7 #6")

Activity.create(name: "Aulas 4 #1")
Activity.create(name: "Aulas 4 #2")
Activity.create(name: "Aulas 4 #3")
Activity.create(name: "Aulas 4 #4")
Activity.create(name: "Aulas 4 #5")
Activity.create(name: "Aulas 4 #6")

Activity.create(name: "Semisotano del Centro de Congresos #1")
Activity.create(name: "Semisotano del Centro de Congresos #2")
Activity.create(name: "Semisotano del Centro de Congresos #3")
Activity.create(name: "Semisotano del Centro de Congresos #4")
Activity.create(name: "Semisotano del Centro de Congresos #5")
Activity.create(name: "Semisotano del Centro de Congresos #6")

Activity.create(name: "Aulas 3 #1")
Activity.create(name: "Aulas 3 #2")
Activity.create(name: "Aulas 3 #3")
Activity.create(name: "Aulas 3 #4")
Activity.create(name: "Aulas 3 #5")
Activity.create(name: "Aulas 3 #6")

Activity.create(name:"Foodbox #1")
Activity.create(name:"Foodbox #2")
Activity.create(name:"Foodbox #3")
Activity.create(name:"Foodbox #4")
Activity.create(name:"Foodbox #5")
Activity.create(name:"Foodbox #6")

Activity.create(name:"Biblio TEC #1")
Activity.create(name:"Biblio TEC #2")
Activity.create(name:"Biblio TEC #3")
Activity.create(name:"Biblio TEC #4")
Activity.create(name:"Biblio TEC #5")
Activity.create(name:"Biblio TEC #6")

Activity.create(name:"CETEC #1")
Activity.create(name:"CETEC #2")
Activity.create(name:"CETEC #3")
Activity.create(name:"CETEC #4")
Activity.create(name:"CETEC #5")
Activity.create(name:"CETEC #6")

Activity.create(name: "Aulas 2 #1")
Activity.create(name: "Aulas 2 #2")
Activity.create(name: "Aulas 2 #3")
Activity.create(name: "Aulas 2 #4")
Activity.create(name: "Aulas 2 #5")
Activity.create(name: "Aulas 2 #6")

Activity.create(name:"Rectoria #1")
Activity.create(name:"Rectoria #2")
Activity.create(name:"Rectoria #3")
Activity.create(name:"Rectoria #4")
Activity.create(name:"Rectoria #5")
Activity.create(name:"Rectoria #6")

Activity.create(name:"Edificio Administrativo y Pabellon Carreta #1")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #2")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #3")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #4")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #5")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #6")

Activity.create(name: "Aulas 1 #1")
Activity.create(name: "Aulas 1 #2")
Activity.create(name: "Aulas 1 #3")
Activity.create(name: "Aulas 1 #4")
Activity.create(name: "Aulas 1 #5")
Activity.create(name: "Aulas 1 #6")

Activity.create(name:"Centrales #1")
Activity.create(name:"Centrales #2")
Activity.create(name:"Centrales #3")
Activity.create(name:"Centrales #4")
Activity.create(name:"Centrales #5")
Activity.create(name:"Centrales #6")

Activity.create(name:"Domo Acuatico #1")
Activity.create(name:"Domo Acuatico #2")
Activity.create(name:"Domo Acuatico #3")
Activity.create(name:"Domo Acuatico #4")
Activity.create(name:"Domo Acuatico #5")
Activity.create(name:"Domo Acuatico #6")

Activity.create(name: "Aulas 6 #1")
Activity.create(name: "Aulas 6 #2")
Activity.create(name: "Aulas 6 #3")
Activity.create(name: "Aulas 6 #4")
Activity.create(name: "Aulas 6 #5")
Activity.create(name: "Aulas 6 #6")

Activity.create(name:"ATLI #1")
Activity.create(name:"ATLI #2")
Activity.create(name:"ATLI #3")
Activity.create(name:"ATLI #4")
Activity.create(name:"ATLI #5")
Activity.create(name:"ATLI #6")

Activity.create(name:"Centro de Biotecnologia #1")
Activity.create(name:"Centro de Biotecnologia #2")
Activity.create(name:"Centro de Biotecnologia #3")
Activity.create(name:"Centro de Biotecnologia #4")
Activity.create(name:"Centro de Biotecnologia #5")
Activity.create(name:"Centro de Biotecnologia #6")

Activity.create(name:"CIAP #1")
Activity.create(name:"CIAP #2")
Activity.create(name:"CIAP #3")
Activity.create(name:"CIAP #4")
Activity.create(name:"CIAP #5")
Activity.create(name:"CIAP #6")

Activity.create(name:"Residencias #1")
Activity.create(name:"Residencias #2")
Activity.create(name:"Residencias #3")
Activity.create(name:"Residencias #4")
Activity.create(name:"Residencias #5")
Activity.create(name:"Residencias #6")

Activity.create(name:"CEDES #1")
Activity.create(name:"CEDES #2")
Activity.create(name:"CEDES #3")
Activity.create(name:"CEDES #4")
Activity.create(name:"CEDES #5")
Activity.create(name:"CEDES #6")
