require 'google_drive'
def write_in_spreadsheet(activity_name)
  Drive.new(ENV["STAFF_SPREADSHEET"]).write_activity_in_spreadsheet(activity_name)
end
Assistance.create(name:"Capas lideres")
Assistance.create(name:"Capas dia 1")
Assistance.create(name:"Capas dia 2")
Assistance.create(name:"HiTec dia 1")
Assistance.create(name:"HiTec dia 2")

User.create(username:"staff", password:"staffs1234", password_confirmation:"staffs1234")
User.create(username:"lider", password:"lideres1234", password_confirmation:"lideres1234")
User.create(username:"team", password:"htteam18", password_confirmation:"htteam18")

Activity.create(name: "Jardin de las Carreras #1")
write_in_spreadsheet("Jardin de las Carreras #1")
Activity.create(name: "Jardin de las Carreras #2")
write_in_spreadsheet("Jardin de las Carreras #2")
Activity.create(name: "Jardin de las Carreras #3")
write_in_spreadsheet("Jardin de las Carreras #3")
Activity.create(name: "Jardin de las Carreras #4")
write_in_spreadsheet("Jardin de las Carreras #4")
Activity.create(name: "Jardin de las Carreras #5")
write_in_spreadsheet("Jardin de las Carreras #5")
Activity.create(name: "Jardin de las Carreras #6")
write_in_spreadsheet("Jardin de las Carreras #6")

Activity.create(name: "Aulas 7 #1")
write_in_spreadsheet("Aulas 7 #1")
Activity.create(name: "Aulas 7 #2")
write_in_spreadsheet("Aulas 7 #2")
Activity.create(name: "Aulas 7 #3")
write_in_spreadsheet("Aulas 7 #3")
Activity.create(name: "Aulas 7 #4")
write_in_spreadsheet("Aulas 7 #4")
Activity.create(name: "Aulas 7 #5")
write_in_spreadsheet("Aulas 7 #5")
Activity.create(name: "Aulas 7 #6")
write_in_spreadsheet("Aulas 7 #6")

Activity.create(name: "Aulas 4 #1")
write_in_spreadsheet("Aulas 4 #1")
Activity.create(name: "Aulas 4 #2")
write_in_spreadsheet("Aulas 4 #2")
Activity.create(name: "Aulas 4 #3")
write_in_spreadsheet("Aulas 4 #3")
Activity.create(name: "Aulas 4 #4")
write_in_spreadsheet("Aulas 4 #4")
Activity.create(name: "Aulas 4 #5")
write_in_spreadsheet("Aulas 4 #5")
Activity.create(name: "Aulas 4 #6")
write_in_spreadsheet("Aulas 4 #6")

Activity.create(name: "Aulas 3 #1")
write_in_spreadsheet("Aulas 3 #1")
Activity.create(name: "Aulas 3 #2")
write_in_spreadsheet("Aulas 3 #2")
Activity.create(name: "Aulas 3 #3")
write_in_spreadsheet("Aulas 3 #3")
Activity.create(name: "Aulas 3 #4")
write_in_spreadsheet("Aulas 3 #4")
Activity.create(name: "Aulas 3 #5")
write_in_spreadsheet("Aulas 3 #5")
Activity.create(name: "Aulas 3 #6")
write_in_spreadsheet("Aulas 3 #6")

Activity.create(name: "Biblio TEC #1")
write_in_spreadsheet("Biblio TEC #1")
Activity.create(name: "Biblio TEC #2")
write_in_spreadsheet("Biblio TEC #2")
Activity.create(name: "Biblio TEC #3")
write_in_spreadsheet("Biblio TEC #3")
Activity.create(name: "Biblio TEC #4")
write_in_spreadsheet("Biblio TEC #4")
Activity.create(name: "Biblio TEC #5")
write_in_spreadsheet("Biblio TEC #5")
Activity.create(name: "Biblio TEC #6")
write_in_spreadsheet("Biblio TEC #6")


Activity.create(name: "Aulas 2 #1")
write_in_spreadsheet("Aulas 2 #1")
Activity.create(name: "Aulas 2 #2")
write_in_spreadsheet("Aulas 2 #2")
Activity.create(name: "Aulas 2 #3")
write_in_spreadsheet("Aulas 2 #3")
Activity.create(name: "Aulas 2 #4")
write_in_spreadsheet("Aulas 2 #4")
Activity.create(name: "Aulas 2 #5")
write_in_spreadsheet("Aulas 2 #5")
Activity.create(name: "Aulas 2 #6")
write_in_spreadsheet("Aulas 2 #6")

Activity.create(name: "Aulas 1 #1")
write_in_spreadsheet("Aulas 1 #1")
Activity.create(name: "Aulas 1 #2")
write_in_spreadsheet("Aulas 1 #2")
Activity.create(name: "Aulas 1 #3")
write_in_spreadsheet("Aulas 1 #3")
Activity.create(name: "Aulas 1 #4")
write_in_spreadsheet("Aulas 1 #4")
Activity.create(name: "Aulas 1 #5")
write_in_spreadsheet("Aulas 1 #5")
Activity.create(name: "Aulas 1 #6")
write_in_spreadsheet("Aulas 1 #6")

Activity.create(name: "Domo Acuatico #1")
write_in_spreadsheet("Domo Acuatico #1")
Activity.create(name: "Domo Acuatico #2")
write_in_spreadsheet("Domo Acuatico #2")
Activity.create(name: "Domo Acuatico #3")
write_in_spreadsheet("Domo Acuatico #3")
Activity.create(name: "Domo Acuatico #4")
write_in_spreadsheet("Domo Acuatico #4")
Activity.create(name: "Domo Acuatico #5")
write_in_spreadsheet("Domo Acuatico #5")
Activity.create(name: "Domo Acuatico #6")
write_in_spreadsheet("Domo Acuatico #6")

Activity.create(name: "Aulas 6 #1")
write_in_spreadsheet("Aulas 6 #1")
Activity.create(name: "Aulas 6 #2")
write_in_spreadsheet("Aulas 6 #2")
Activity.create(name: "Aulas 6 #3")
write_in_spreadsheet("Aulas 6 #3")
Activity.create(name: "Aulas 6 #4")
write_in_spreadsheet("Aulas 6 #4")
Activity.create(name: "Aulas 6 #5")
write_in_spreadsheet("Aulas 6 #5")
Activity.create(name: "Aulas 6 #6")
write_in_spreadsheet("Aulas 6 #6")

Activity.create(name: "ATLI #1")
write_in_spreadsheet("ATLI #1")
Activity.create(name: "ATLI #2")
write_in_spreadsheet("ATLI #2")
Activity.create(name: "ATLI #3")
write_in_spreadsheet("ATLI #3")
Activity.create(name: "ATLI #4")
write_in_spreadsheet("ATLI #4")
Activity.create(name: "ATLI #5")
write_in_spreadsheet("ATLI #5")
Activity.create(name: "ATLI #6")
write_in_spreadsheet("ATLI #6")

Activity.create(name: "Foodbox #1")
write_in_spreadsheet("Foodbox #1")
Activity.create(name: "Foodbox #2")
write_in_spreadsheet("Foodbox #2")
Activity.create(name: "Foodbox #3")
write_in_spreadsheet("Foodbox #3")
Activity.create(name: "Foodbox #4")
write_in_spreadsheet("Foodbox #4")
Activity.create(name: "Foodbox #5")
write_in_spreadsheet("Foodbox #5")
Activity.create(name: "Foodbox #6")
write_in_spreadsheet("Foodbox #6")

Activity.create(name: "CETEC #1")
write_in_spreadsheet("CETEC #1")
Activity.create(name: "CETEC #2")
write_in_spreadsheet("CETEC #2")
Activity.create(name: "CETEC #3")
write_in_spreadsheet("CETEC #3")
Activity.create(name: "CETEC #4")
write_in_spreadsheet("CETEC #4")
Activity.create(name: "CETEC #5")
write_in_spreadsheet("CETEC #5")
Activity.create(name: "CETEC #6")
write_in_spreadsheet("CETEC #6")

Activity.create(name: "Rectoria #1")
write_in_spreadsheet("Rectoria #1")
Activity.create(name: "Rectoria #2")
write_in_spreadsheet("Rectoria #2")
Activity.create(name: "Rectoria #3")
write_in_spreadsheet("Rectoria #3")
Activity.create(name: "Rectoria #4")
write_in_spreadsheet("Rectoria #4")
Activity.create(name: "Rectoria #5")
write_in_spreadsheet("Rectoria #5")
Activity.create(name: "Rectoria #6")
write_in_spreadsheet("Rectoria #6")

Activity.create(name: "Centrales #1")
write_in_spreadsheet("Centrales #1")
Activity.create(name: "Centrales #2")
write_in_spreadsheet("Centrales #2")
Activity.create(name: "Centrales #3")
write_in_spreadsheet("Centrales #3")
Activity.create(name: "Centrales #4")
write_in_spreadsheet("Centrales #4")
Activity.create(name: "Centrales #5")
write_in_spreadsheet("Centrales #5")
Activity.create(name: "Centrales #6")
write_in_spreadsheet("Centrales #6")

Activity.create(name: "CIAP #1")
write_in_spreadsheet("CIAP #1")
Activity.create(name: "CIAP #2")
write_in_spreadsheet("CIAP #2")
Activity.create(name: "CIAP #3")
write_in_spreadsheet("CIAP #3")
Activity.create(name: "CIAP #4")
write_in_spreadsheet("CIAP #4")
Activity.create(name: "CIAP #5")
write_in_spreadsheet("CIAP #5")
Activity.create(name: "CIAP #6")
write_in_spreadsheet("CIAP #6")

Activity.create(name: "Residencias #1")
write_in_spreadsheet("Residencias #1")
Activity.create(name: "Residencias #2")
write_in_spreadsheet("Residencias #2")
Activity.create(name: "Residencias #3")
write_in_spreadsheet("Residencias #3")
Activity.create(name: "Residencias #4")
write_in_spreadsheet("Residencias #4")
Activity.create(name: "Residencias #5")
write_in_spreadsheet("Residencias #5")
Activity.create(name: "Residencias #6")
write_in_spreadsheet("Residencias #6")

Activity.create(name: "CEDES #1")
write_in_spreadsheet("CEDES #1")
Activity.create(name: "CEDES #2")
write_in_spreadsheet("CEDES #2")
Activity.create(name: "CEDES #3")
write_in_spreadsheet("CEDES #3")
Activity.create(name: "CEDES #4")
write_in_spreadsheet("CEDES #4")
Activity.create(name: "CEDES #5")
write_in_spreadsheet("CEDES #5")
Activity.create(name: "CEDES #6")
write_in_spreadsheet("CEDES #6")

Activity.create(name: "Semisotano del Centro de Congresos #1")
write_in_spreadsheet("Semisotano del Centro de Congresos #1")
Activity.create(name: "Semisotano del Centro de Congresos #2")
write_in_spreadsheet("Semisotano del Centro de Congresos #2")
Activity.create(name: "Semisotano del Centro de Congresos #3")
write_in_spreadsheet("Semisotano del Centro de Congresos #3")
Activity.create(name: "Semisotano del Centro de Congresos #4")
write_in_spreadsheet("Semisotano del Centro de Congresos #4")
Activity.create(name: "Semisotano del Centro de Congresos #5")
write_in_spreadsheet("Semisotano del Centro de Congresos #5")
Activity.create(name: "Semisotano del Centro de Congresos #6")
write_in_spreadsheet("Semisotano del Centro de Congresos #6")

Activity.create(name:"Edificio Administrativo y Pabellon Carreta #1")
write_in_spreadsheet("Edificio Administrativo y Pabellon Carreta #1")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #2")
write_in_spreadsheet("Edificio Administrativo y Pabellon Carreta #2")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #3")
write_in_spreadsheet("Edificio Administrativo y Pabellon Carreta #3")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #4")
write_in_spreadsheet("Edificio Administrativo y Pabellon Carreta #4")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #5")
write_in_spreadsheet("Edificio Administrativo y Pabellon Carreta #5")
Activity.create(name:"Edificio Administrativo y Pabellon Carreta #6")
write_in_spreadsheet("Edificio Administrativo y Pabellon Carreta #6")

Activity.create(name:"Centro de Biotecnologia #1")
write_in_spreadsheet("Centro de Biotecnologia #1")
Activity.create(name:"Centro de Biotecnologia #2")
write_in_spreadsheet("Centro de Biotecnologia #2")
Activity.create(name:"Centro de Biotecnologia #3")
write_in_spreadsheet("Centro de Biotecnologia #3")
Activity.create(name:"Centro de Biotecnologia #4")
write_in_spreadsheet("Centro de Biotecnologia #4")
Activity.create(name:"Centro de Biotecnologia #5")
write_in_spreadsheet("Centro de Biotecnologia #5")
Activity.create(name:"Centro de Biotecnologia #6")
write_in_spreadsheet("Centro de Biotecnologia #6")

Activity.create(name:"Asesoria y Consejeria")
write_in_spreadsheet("Asesoria y Consejeria")
Activity.create(name:"Servicio Social")
write_in_spreadsheet("Servicio Social")
Activity.create(name:"CVC")
write_in_spreadsheet("CVC")
Activity.create(name:"Programas Internacionales")
write_in_spreadsheet("Programas Internacionales")
Activity.create(name:"Movilidad")
write_in_spreadsheet("Movilidad")
Activity.create(name:"Servicio de Salud")
write_in_spreadsheet("Servicio de Salud")
Activity.create(name:"TecStore")
write_in_spreadsheet("TecStore")
Activity.create(name:"Prevencion")
write_in_spreadsheet("Prevencion")
Activity.create(name:"Ecosistema Emprendedor")
write_in_spreadsheet("Ecosistema Emprendedor")
Activity.create(name:"Biblio Tec")
write_in_spreadsheet("Biblio Tec")
Activity.create(name:"Punto Blanco")
write_in_spreadsheet("Punto Blanco")
Activity.create(name:"Arte Cultura")
write_in_spreadsheet("Arte Cultura")
Activity.create(name:"Campus Accesible")
write_in_spreadsheet("Campus Accesible")
Activity.create(name:"Arte y Cultura + Deportes")
write_in_spreadsheet("Arte y Cultura + Deportes")
Activity.create(name:"Punto Azul")
write_in_spreadsheet("Punto Azul")
Activity.create(name:"Deportes")
write_in_spreadsheet("Deportes")
Activity.create(name:"Seguridad")
write_in_spreadsheet("Seguridad")
Activity.create(name:"Residencias")
write_in_spreadsheet("Residencias")
